config/routes.rb
Paired::Application.routes.draw do

  resources :auths
  resources :user_interests
  resources :interests
  resources :users
  get 'users/linkedin_create' => 'users#linkedin_create'

  get '/auth/:provider/callback', to: 'users#linkedin_create' 

end

app/models/user.rb
class User < ActiveRecord::Base
    before_save { self.email = email.downcase }
    attr_accessor :password, :avatar
    

    has_many :user_interests
    has_many :interests, through: :user_interests
    accepts_nested_attributes_for :user_interests

    validates :first_name, presence: true, length: { maximum: 50 }
    validates :last_name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
              uniqueness: { case_sensitive: false } 
    
    validates :password, presence: true, length: { minimum: 4 }, :on => :create

    has_attached_file :avatar, :styles => {:thumb => '50x50#', :small => '100x100#', :medium => '125x125>'}, :default_url => "/images/peared.jpg"

    crop_attached_file :avatar


    validates_attachment_size :avatar, :less_than => 5.megabytes
    validates_attachment_content_type :avatar, :content_type => ['image/jpeg', 'image/png']

    def full_name
        "#{first_name} #{last_name}"
    end

    geocoded_by :location
    after_validation :geocode

    def self.by_letter(letter)
        where("last_name LIKE ?", "#{letter}%").order(:last_name)
    end

    def self.search(search)
        if search
            find(:all, :conditions => ['first_name LIKE ? OR last_name LIKE ? OR interests LIKE ?', "%#{search.capitalize}%", "%#{search.capitalize}%", "%#{search.downcase}%"])
        else
            find(:all)
        end
    end

    def self.from_omniauth(data)
        if User.where(email: data["info"]["email"]).empty?
            user = User.new
            user.email = data["info"]["email"]
            user.first_name = data["info"]["first_name"]
            user.last_name = data["info"]["last_name"]
            user.location = data["info"]["location"]["name"]
            user.password = SecureRandom.urlsafe_base64(n=6)
            user.save!
            return false
        else
            return true
        end
    end
    
    def authenticated? pwd
        self.hashed_password ==
        BCrypt::Engine.hash_secret(pwd, self.salt)
    end

    before_save :hash_the_password
  
    private 

    def hash_the_password
        unless self.password == nil
          self.salt = BCrypt::Engine.generate_salt
          self.hashed_password = BCrypt::Engine.hash_secret self.password, self.salt
          self.password = nil
        end 
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    respond_to do |format|
        format.html { @users = User.all }
        format.json { render json: User.all   }
    end

    # @users = User.all
      @hash = Gmaps4rails.build_markers(@users) do |user, marker|
      latLng = Geocoder.coordinates(@user)
      marker.lat user.latitude
      marker.lng user.longitude 
      # marker.infowindow user.description
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      UserMailer.welcome(@user.id).deliver
      session[:user_id] = @user.id  
      flash[:notice] = "user was successfully created"
      redirect_to edit_user_path(current_user)
    else
      render action: 'new'
      flash[:error] = "aww shucks, user was not created!"
    end
  end

  def linkedin_create
    data = request.env['omniauth.auth']
    if User.from_omniauth(data) == false
        user = User.find_by(email: data["info"]["email"])
        session[:user_id] = user.id
        redirect_to edit_user_path(current_user) 
    else
        user = User.find_by(email: data["info"]["email"])
        session[:user_id] = user.id
        redirect_to users_path
    end
  end


  def edit
    @user = User.find(params[:id])
    @user_interests = current_user.user_interests
  end

  def update
    @user = User.find(params[:id])

    if params[:user][:avatar]
      @user.update_attributes(avatar: params[:user][:avatar])
    end

    if @user.update(params.require(:user).permit(:first_name, :last_name, :username, :location, :email
      ))
      session[:user_id] = @user.id
      redirect_to @user
      flash[:notice] = "Your profile was successfully updated."
    else
      render action: 'edit'
      flash[:error] = "Your profile was not able to be updated, please make sure to fill out all of the fields."
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = "Your user was destroyed"
    redirect_to users_url 
  end


  private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :username, :location, :email, :password, :avatar
      )
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      <p><u>The form contains <%= pluralize(@user.errors.count, "error") %>.</u></p>
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
      <br />
        <br />
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_map.html.erb
<input id="pac-input" class="controls" type="text" placeholder="Search Box">
<div id="map-canvas"></div>
<script type="text/javascript">
    var marker; // get the json obj + parse for latlong
    
function initialize() {
        handler = Gmaps.build('Google');
        handler.buildMap({ provider: {provider_id: 'AIzaSyD0669qE8-xHbI-414wmX3_yLJ6q-r3bFY'}, internal: {id: 'map-canvas'}}, function(){
        markers = handler.addMarkers(<%=raw @hash.to_json %>);

          handler.bounds.extendWith(markers);
          handler.fitMapToBounds();
        });
    }

    google.maps.event.addDomListener(window, 'load', initialize);
</script>

app/views/users/_signUpUser.html.erb
<div class="signUpUser">
    <div class="small-12 medium-10 large-8 columns" id="signUp">
        <%= form_for @user, :id => "myForm", :html => {"data-abide" => ''} do |u| %>
            <%= render partial: '/layouts/error_messages' %>
            <div class="row">
                <div class="small-12 medium-7 large-6 columns">
                    <label><u>First name: </u><br /><small>Required</small>
                        <%= u.text_field :first_name, :placeholder => "Enter your first name" %>
                    </label>
                    <small class="error">Please enter your email.</small>
                </div>
            </div>

           <div class="row">
                <div class="small-12 medium-7 large-6 columns">
                    <label><u>Last name: </u><br /><small>Required</small>
                        <%= u.text_field :last_name, :placeholder => "Enter your last name" %>
                    </label>
                    <small class="error">Please enter your email.</small>
                </div>
            </div>

            <div class="row">
                <div class="small-12 medium-7 large-6 columns">
                    <label><u>Email: </u><br /><small>Required</small>
                        <%= u.text_field :email, :placeholder => "Enter your email" %>
                    </label>
                    <small class="error">Please enter your email.</small>
                </div>
            </div>

            <div class="row">
                <div class="small-12 medium-7 large-6 columns">
                    <label><u>Password: </u><br /><small>Required</small>
                        <%= u.password_field :password, :placeholder => "6+ characters" %>
                    </label>
                    <small class="error">Please enter your email.</small>
                </div>
            </div>

            <div class="row">
                <div class="small-12 medium-7 large-6 columns">
                    <label id="numero5"> <br />
                        <%= u.submit "Sign up!" %> <br />
                        <%= link_to "Sign Up with LinkedIn", "/auth/linkedin" %> <br /> 
                        <a href="#" data-reveal-id="myModal">Log In</a>

                    </label>
                </div>
            </div>
        <% end %>
    </div>

    <br />
    <br />

    <div class="small-12 medium-12 large-12 columns">
        <div class="signInParagraph" id="numero1">
            <p class="signInList">
                <div class="small-12 medium-12 large-12 columns" id="meetUp">
                    <h3 class="paragraphTitle"  id="numero1"><u>Why you want to use this site: </u></h3>
                    <br />
                    <label> <br />
                        <div class="small-12 medium-6 large-3 columns">
                            <p id="innerP">Meet other people with whom to program!</p>
                        </div>

                        <div class="small-12 medium-6 large-7 columns">
                            <%= image_tag("meet.jpg", :alt => "thumbs up pic") %>
                        </div>
                    </label>
                </div>

                <div class="small-12 medium-12 large-12 columns" id="learn">
                    <h3 class="reason1"><u>Reasons to use this site: </u></h3>
                    <br />
                    <label id="numero2"> <br />
                        <div class="small-12 medium-6 large-3 columns">
                            <p id="innerP">You will learn faster with someone else.</p>
                        </div>

                        <div class="small-12 medium-6 large-7 columns">
                            <%= image_tag("learning.jpg", :alt => "heads together pic") %>
                        </div>
                    </label>
                </div>

                <div class="small-12 medium-12 large-12 columns" id="share">
                    <h3 class="reason2"><u>Reasons to use this site: </u></h3>
                    <br />
                    <label id="numero3"> <br />
                        <div class="small-12 medium-6 large-3 columns">
                            <p id="innerP">Share knowledge with each other.</p>
                        </div>

                        <div class="small-12 medium-6 large-7 columns">
                            <%= image_tag("share.jpg", :alt => "jack russel on a computer pic") %>
                        </div>
                    </label>
                </div>

                <div class="small-12 medium-12 large-12 columns" id="focus">
                    <h3 class="reason3"><u>Reasons to use this site: </u></h3>
                    <br />
                    <label id="numero4"> <br />
                        <div class="small-12 medium-6 large-3 columns">
                            <p id="innerP">Focus on the problem at hand.</p>
                        </div>

                        <div class="small-12 medium-6 large-7 columns">
                            <%= image_tag("focus.jpg", :alt => "tic toc pic") %>
                        </div>
                    </label>
                </div>
            </p>
        
        </div>
    </div>
</div>

<ol class="joyride-list" data-joyride>
  <li data-id="firstStop" data-text="Next" data-options="tip_location: top">
    <p>Welcome to Paired!</p>
  </li>
  <li data-id="numero1" data-class="custom so-awesome" data-text="Next">
    <h4>Stop #1</h4>
    <p>Meet a pair.</p>
  </li>
  <li data-id="numero2" data-button="Next" data-options="tip_location:top;tip_animation:fade">
    <h4>Stop #2</h4>
    <p>Learn Faster</p>
  </li>
  <li data-id="numero3" data-button="Next" data-options="tip_location:top;tip_animation:fade">
    <h4>Stop #3</h4>
    <p>Share knowledge</p>
  </li>
  <li data-id="numero4" data-button="Next" data-options="tip_location:top;tip_animation:fade">
    <h4>Stop #4</h4>
    <p>Focus more</p>
  </li>
  <li data-id="numero5" data-button="Next" data-options="tip_location:top;tip_animation:fade">
    <h4>Stop #5</h4>
    <p>Sign up, tell us what you know, and connect.</p>
  </li>
  <li data-button="End">
    <h4>Stop #6</h4>
    <p>And meet your pair!</p>
  </li>
</ol>


<div id="myModal" class="reveal-modal" data-reveal>
  <h2 id="title" >Log In</h2>
    <div>
        <%= form_for @user, {url:"/auths", method:"post"} do |u| %>
            <div class="row">
                <div class="small-12 medium-6 large-4 columns">
                    <label> Email:<br />
                        <%= u.text_field :email, :placeholder => "Enter your email" %>
                    </label>
                </div>
            </div>


            <div class="row">
                <div class="small-12 medium-6 large-4 columns">
                    <label> Password:<br />
                        <%= u.password_field :password, :placeholder => "Enter your password" %>
                    </label>
                </div>
            </div>

            
            <div>
                <%= u.submit "Log in" %> | 
                <%= link_to "Sign up", new_user_path %> 
            </div>
        <% end %>
    </div>  
  <a class="close-reveal-modal">&#215;</a>
</div>

<script>
$('#myForm')
  .on('invalid', function () {
    var invalid_fields = $(this).find('[data-invalid]');
    console.log(invalid_fields);
  })
  .on('valid', function () {
    console.log('valid!');
  });
</script>

app/views/users/edit.html.erb
<%= render partial: '/layouts/navbar' %>


<h1 id="title"><u>My Profile</u></h1>

<%= render template: "user_interests/new" %>

<h1><%=current_user.first_name %>'s languages and skill levels</h1>
<!-- where else could this logic be done?  -->


<% unless @user_interests == nil %>
    <div>
        <% @user_interests.each do |ui| %>
            <%= Interest.find_by(id: ui.interest_id).name %> 
            <%= ui.skill_level %>
            <%= button_to "Delete", ui, method: :delete, class: "button tiny alert"%>
            <br>
        <% end %> 
        <br>
        <br>
    </div> 
<% end %> 



<div>
    <%= form_for @user, :url => user_path, :html => { :multipart => true } do |u|%>
        <%= render partial: '/layouts/error_messages' %>
        <div class="row">
            <div class="small-12 medium-6 large-4 columns">
                <label>First name:<br /><small>Required</small>
                    <%= u.text_field :first_name, :placeholder => "Enter your first name" %>
                </label>
                <!-- <small class="error">Please enter your first name.</small> -->
            </div>
        </div>


    
        <div class="row">
            <div class="small-12 medium-6 large-4 columns">
                <label>Last name:<br /><small>Required</small>
                    <%= u.text_field :last_name, :placeholder => "Enter your last name" %>
                </label>
                <!-- <small class="error">Please enter your last name.</small> -->
            </div>

        </div>
        

        <div class="row">
            <div class="small-12 medium-6 large-4 columns">
                <label>Username:<br />
                    <%= u.text_field :username, :placeholder => "Enter your username" %>
                </label>
            </div>
        </div>
        
        <div class="row">
            <div class="small-12 medium-6 large-4 columns">
                <label> Photo:<br /><small>required</small>
                    <%= u.file_field :avatar, :placeholder => "Add a photo " %>
                </label>
            </div>
        </div>

        <div class="row">
            <div class="small-12 medium-6 large-4 columns">
                <label> Location:<br /><small>required</small>
                    <%= u.text_field :location, :placeholder => "Enter your city" %>
                </label>
            </div>
        </div>
        

        <div class="row">
            <div class="small-12 medium-6 large-4 columns">
                <label> Email:<br /><small>required</small>
                    <%= u.text_field :email, :placeholder => "Enter your email" %>
                </label>
               <!--  <small class="error">Please enter your email.</small> -->
            </div>
        </div>
        
        
        <div class="row">
            <div class="small-12 medium-6 large-4 columns">
                <label> <br />
                    <%= u.submit "Finish profile" %>
                </label>
            </div>
        </div>

    <% end %>
</div>

app/views/users/index.html.erb
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD0669qE8-xHbI-414wmX3_yLJ6q-r3bFY&sensor=true"></script>
<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?libraries=places&sensor=true"></script>
<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" type="text/javascript"></script>

<%= render partial: '/layouts/navbar' %>

<h1 id="title"><u>Profiles</u></h1>

<script type="text/javascript">
  $(document).ready(function() {
    $('#languageFilter li').on('click', 'a', function() {
      language = $(this).attr('id');
      $('#container').isotope({ filter: ("."+language) });
      console.log(language);
    });
  });
</script>



<div id="languageFilter"> 
  <a href="#" class="button" data-dropdown="drop">Language &raquo;</a>
  <ul id="drop" class="tiny f-dropdown" data-dropdown-content>
    <% Interest.all.each do |interest| %> 
      <li><a href="#" id="<%= interest.name %>"> <%= interest.name %></a></li>
    <% end %> 
  </ul>
</div>


<div id="container">
    <% @users.each do |u| %>
      <div class="flip-container <% u.interests.each do |interest| %> <%= interest.name %> <% end %>" ontouchstart="this.classList.toggle('hover');">
        <div class="flipper">
            <div class="front">
                    <span class="name"><%= u.full_name %></span>

            </div>
                <div class="back">
                    <div class="back-logo" style="background: url(<%= u.avatar_file_size ? u.avatar.url(:medium) : "/assets/peared.jpg" %>) 0 0 no-repeat">

                    </div>
                    <div class="back-title"><%= u.full_name %></div>
                    <p>
                        <%= u.location  %>
                        <br />
                        <%= u.email  %>
                        <br /> 
                    </p>
                </div>
        </div>
      </div>
    <% end %>
</div>


<%= render partial: 'map' %>

app/views/users/new.html.erb
<body class="signUpPage">
<!--  background-class="signUpPage" -->
<h1 id="title" class="profileTitle"><strong><u>Paired</u></strong></h1>
<h4 id="firstStop" class="profileTag">Learn faster with a friend</h4>
<h4 class="newUser">Sign up!</h4>

<div class="signUpUser">
    <div class="small-12 medium-10 large-8 columns" id="signUp">
        <%= form_for @user do |u| %>
            <%#= render partial: '/layouts/error_messages' %>
            <div class="row">
                <div class="small-12 medium-7 large-6 columns">
                    <label><u>First name: </u><br /><small>Required</small>
                        <%= u.text_field :first_name, :placeholder => "Enter your first name" %>
                    </label>
                    <!-- <small class="error">Please enter your email.</small> -->
                </div>
            </div>

           <div class="row">
                <div class="small-12 medium-7 large-6 columns">
                    <label><u>Last name: </u><br /><small>Required</small>
                        <%= u.text_field :last_name, :placeholder => "Enter your last name" %>
                    </label>
                    <!-- <small class="error">Please enter your email.</small> -->
                </div>
            </div>

            <div class="row">
                <div class="small-12 medium-7 large-6 columns">
                    <label><u>Email: </u><br /><small>Required</small>
                        <%= u.text_field :email, :placeholder => "Enter your email" %>
                    </label>
                    <!-- <small class="error">Please enter your email.</small> -->
                </div>
            </div>

            <div class="row">
                <div class="small-12 medium-7 large-6 columns">
                    <label><u>Password: </u><br /><small>Required</small>
                        <%= u.password_field :password, :placeholder => "6+ characters" %>
                    </label>
                    <!-- <small class="error">Please enter your password.</small> -->
                </div>
            </div>

            <div class="row">
                <div class="small-12 medium-7 large-6 columns">

                    <label id="numero5"> <br />
                        <%= u.submit "Sign up!" %> <br />
                        <%= link_to "Sign Up with LinkedIn", "/auth/linkedin" %> <br /> 
                        <a href="#" data-reveal-id="myModal">Log In</a>
                    </label>
                </div>
            </div>
        <% end %>
    </div>

    <br />
    <br />

    <div class="small-12 medium-12 large-12 columns">
        <div class="signInParagraph" id="numero1">
            <p class="signInList">
                <div class="small-12 medium-12 large-12 columns" id="meetUp">
                    <h3 class="paragraphTitle"  id="numero1"><u>Why you want to use this site: </u></h3>
                    <br />
                    <label> <br />
                        <div class="small-12 medium-6 large-3 columns">
                            <p id="innerP">Meet other people with whom to program!</p>
                        </div>

                        <div class="small-12 medium-6 large-7 columns">
                            <%= image_tag("meet.jpg", :alt => "thumbs up pic") %>
                        </div>
                    </label>
                </div>

                <div class="small-12 medium-12 large-12 columns" id="learn">
                    <h3 class="reason1"><u>Reasons to use this site: </u></h3>
                    <br />
                    <label id="numero2"> <br />
                        <div class="small-12 medium-6 large-3 columns">
                            <p id="innerP">You will learn faster with someone else.</p>
                        </div>

                        <div class="small-12 medium-6 large-7 columns">
                            <%= image_tag("learning.jpg", :alt => "heads together pic") %>
                        </div>
                    </label>
                </div>

                <div class="small-12 medium-12 large-12 columns" id="share">
                    <h3 class="reason2"><u>Reasons to use this site: </u></h3>
                    <br />
                    <label id="numero3"> <br />
                        <div class="small-12 medium-6 large-3 columns">
                            <p id="innerP">Share knowledge with each other.</p>
                        </div>

                        <div class="small-12 medium-6 large-7 columns">
                            <%= image_tag("share.jpg", :alt => "jack russel on a computer pic") %>
                        </div>
                    </label>
                </div>

                <div class="small-12 medium-12 large-12 columns" id="focus">
                    <h3 class="reason3"><u>Reasons to use this site: </u></h3>
                    <br />
                    <label id="numero4"> <br />
                        <div class="small-12 medium-6 large-3 columns">
                            <p id="innerP">Focus on the problem at hand.</p>
                        </div>

                        <div class="small-12 medium-6 large-7 columns">
                            <%= image_tag("focus.jpg", :alt => "tic toc pic") %>
                        </div>
                    </label>
                </div>
            </p>
        
        </div>
    </div>
</div>




<ol class="joyride-list" data-joyride>
  <li data-id="firstStop" data-text="Next" data-options="tip_location: top">
    <p>Welcome to Paired!</p>
  </li>
  <li data-id="numero1" data-class="custom so-awesome" data-text="Next">
    <h4>Stop #1</h4>
    <p>Meet a pair.</p>
  </li>
  <li data-id="numero2" data-button="Next" data-options="tip_location:top;tip_animation:fade">
    <h4>Stop #2</h4>
    <p>Learn Faster</p>
  </li>
  <li data-id="numero3" data-button="Next" data-options="tip_location:top;tip_animation:fade">
    <h4>Stop #3</h4>
    <p>Share knowledge</p>
  </li>
  <li data-id="numero4" data-button="Next" data-options="tip_location:top;tip_animation:fade">
    <h4>Stop #4</h4>
    <p>Focus more</p>
  </li>
  <li data-id="numero5" data-button="Next" data-options="tip_location:top;tip_animation:fade">
    <h4>Stop #5</h4>
    <p>Sign up, tell us what you know, and connect.</p>
  </li>
  <li data-button="End">
    <h4>Stop #6</h4>
    <p>And meet your pair!</p>
  </li>
</ol>


<div id="myModal" class="reveal-modal" data-reveal>
  <h2 id="title" >Log In</h2>
    <div>
        <%= form_for @user, {url:"/auths", method:"post"} do |u| %>
            <div class="row">
                <div class="small-12 medium-6 large-4 columns">
                    <label> Email:<br />
                        <%= u.text_field :email, :placeholder => "Enter your email" %>
                    </label>
                </div>
            </div>


            <div class="row">
                <div class="small-12 medium-6 large-4 columns">
                    <label> Password:<br />
                        <%= u.password_field :password, :placeholder => "Enter your password" %>
                    </label>
                </div>
            </div>

            
            <div>
                <%= u.submit "Log in" %> | 
                <%= link_to "Sign up", new_user_path %> 
            </div>
        <% end %>
    </div>  
  <a class="close-reveal-modal">&#215;</a>
</div>

<script>
$('#myForm')
  .on('invalid', function () {
    var invalid_fields = $(this).find('[data-invalid]');
    console.log(invalid_fields);
  })
  .on('valid', function () {
    console.log('valid!');
  });
</script>

app/views/users/post.html.erb
<h1>Users#post</h1>
<p>Find me in app/views/users/post.html.erb</p>

app/views/users/show.html.erb
<%= render partial: '/layouts/navbar' %>
<h1 id="title"><u>My Profile</u></h1>
<h3 id="myProfile1">
    <%= current_user ? current_user.username : "(logged in)" %> 
</h3>

  
  <div>
    <u id="myProfile">Name:</u> <br />
    <%= current_user.full_name %><br />
    <% if current_user.avatar_file_size %>
        <%= image_tag current_user.avatar.url(:medium) if current_user.avatar.file? %>
    <% end %>
    <br/>
    <u id="myProfile">Email:</u> <br />
    <%= current_user.email %><br />
    <u id="myProfile">Location:</u><br /> 
    <%= current_user.location %><br />
    <u id="myProfile">Interests:</u><br />
    <% unless current_user.interests.empty? %>
        <%= current_user.interests.first.name %>
    <% end %>
  </div>
<br />
<%= link_to "Home", users_path %><br />