config/routes.rb
Paired::Application.routes.draw do

  resources :auths
  resources :user_interests
  resources :interests
  resources :users
  get 'users/linkedin_create' => 'users#linkedin_create'

  get '/auth/:provider/callback', to: 'users#linkedin_create' 

end

app/views/layouts/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1><a href="#">Paired</a></h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>
  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <li class="active"><a href="#">Welcome back, <%= current_user.first_name %></a></li>
      <li class="has-dropdown">
        <a href="#">Profile Options</a>
        <ul class="dropdown">
          <li><%= link_to "Home", users_path %></li>
          <li><%= link_to "My Profile", user_path(current_user), method: 'get' %></li>
          <li><%= link_to "Edit", edit_user_path(current_user) %></li>
          <li><%= link_to "Log Out", new_auth_path, method: 'delete' %></li>
        </ul>
      </li>
    </ul>

  </section>
  
</nav>


<!-- <div>
    <li class="has-form">
        <div class="row collapse">
            <div class="large-4 medium-5 small-7 columns">
              <input type="text" placeholder="Find Stuff">
            </div>
            <div class="large-1 medium-2 small-3 columns">
              <a href="#" class="alert button expand">Search</a>
            </div>
        </div>
    </li>
</div> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Paired" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "jquery" %>
    <%= javascript_include_tag 'isotope.min' %>
    <%= csrf_meta_tags %>

  </head>

  <body>

    <main role="main">
        <%= javascript_include_tag "application" %>
        <%= yield %>

        <%#= params %>
 
        <%# if current_user %>
             <%#= current_user.email %>
        <%# else %>
            <%#= "no current user" %>
        <%# end %>
    </main>

    
    </body>
</html>